version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing dependencies"
      - mvn -version

  pre_build:
    commands:
      - echo "Build started on $(date)"

  build:
    commands:
      - echo "Running Selenium tests"
      - mvn clean test -Dheadless=true

  post_build:
    commands:
      - echo "Uploading Extent Report to S3"
      - aws s3 cp target/extent-reports/ s3://niladri-selenium-reports-2026/extent-reports/ --recursive

artifacts:
  files:
    - target/extent-reports/**/*