version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing dependencies"
      - mvn -version

  pre_build:
    commands:
      - echo "Build started on $(date)"

  build:
    commands:
      - echo "Running Selenium tests"
      - mvn clean test -Dheadless=true

  post_build:
    commands:
      - echo "Uploading Latest Extent Report to S3"
      - aws s3 cp latest-report/ s3://niladri-selenium-reports-2026/extent-reports/latest/ --recursive --acl public-read

      - echo "Uploading Timestamp Reports to S3"
      - aws s3 cp reports/ s3://niladri-selenium-reports-2026/extent-reports/history/ --recursive --acl public-read

      - echo "Report URL:"
      - echo "https://niladri-selenium-reports-2026.s3.ap-south-1.amazonaws.com/extent-reports/latest/index.html"

artifacts:
  files:
    - latest-report/**/*
    - reports/**/*